# Generated by Django 5.0.3 on 2024-03-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedidos',
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
    ]
